version: "3"

tasks:
  helm-pull:
    cmds:
      - kluctl helm-pull
    desc: "Pre-pull helm charts"

  render-staging:
    cmds:
      - kluctl render -t staging --print-all | yq
    desc: "Render resource yaml with staging values"

  deploy-staging:
    cmds:
      - kluctl deploy -t staging
    desc: "Deploy staging configuration"

  delete-staging:
    cmds:
      - kluctl delete -t staging
    desc: "Render resource yaml with staging values"

  render-production:
    cmds:
      - kluctl render -t production --print-all | yq
    desc: "Render resource yaml with production values"

  deploy-production:
    cmds:
      - kluctl deploy -t production
    desc: "Deploy production configuration"

  delete-production:
    cmds:
      - kluctl delete -t production
    desc: "Render resource yaml with production values"
