apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-golang
  namespace: demo-app-{{ args.environment }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ sharedVars.hostName }}`) && PathPrefix(`/api/golang`)
      middlewares:
        - name: strip-api-prefixes
      services:
        - kind: Service
          name: api-golang
          port: 8080
          scheme: http
