apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: client-react-nginx
  namespace: demo-app-{{ args.environment }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ sharedVars.hostName }}`)
      services:
        - kind: Service
          name: client-react-nginx
          port: 8080
          scheme: http
