apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-node
  namespace: demo-app-{{ args.environment }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ sharedVars.hostName }}`) && PathPrefix(`/api/node`)
      middlewares:
        - name: strip-api-prefixes
      services:
        - kind: Service
          name: api-node
          port: 3000
          scheme: http
