apiVersion: v1
kind: Service
metadata:
  name: api-node
  namespace: demo-app-{{ args.environment }}
spec:
  selector:
    app: api-node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
