vars:
  - file: config/{{ args.environment }}.yaml

deployments:
  - path: namespaces
  - barrier: true
  - include: third-party
  - barrier: true # postgres depends on cloudnative-pg being installed
  - include: services

commonLabels:
  demo/app: "demo-app"
