apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefixes-node
  namespace: demo-app-{{ args.environment }}
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /api/node
