# ⛔️ DONT PUT SECRET FILES IN VCS
# Creating this secret here is a bit of a hack to ensure it exists before
# the db-migrator job which runs as a pre-deploy hook for api-golang
apiVersion: v1
kind: Secret
metadata:
  name: db-migrator-password
  namespace: demo-app-{{ args.environment }}
  annotations:
    kluctl.io/hook: pre-deploy
    kluctl.io/hook-weight: 1
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:foobarbaz@cnpg-minimal-rw.postgres.svc.cluster.local:5432/postgres
